#!/bin/bash

# 32bits:
# LWARCH=32-bit
# LWEXEC=lispworks-7-0-0-x86-darwin

LWARCH=64-bit
LWEXEC=lispworks-7-1-0-amd64-darwin

OM_VERSION="7.0"
# APP_FOLDER="OM "$OM_VERSION
BUILD_FOLDER="../BUILD"
APP_NAME="o7"
APP_FOLDER="$BUILD_FOLDER"/"$APP_NAME"
DMG_NAME="o7-macOS"

deliver_app()
{
echo "***************************************************"
echo "COMPILING STANDALONE EXE"
echo "***************************************************"

	rm -rf ./om/*.app/
	/Applications/LispWorks\ 7.1\ \($LWARCH\)/LispWorks\ \($LWARCH\).app/Contents/MacOS/$LWEXEC -build ./om/build/deliver.lisp
}


# deliver_app MUST have been called before..
pack_app()
{
echo "***************************************************"
echo "Packing $APP_FOLDER"
echo "***************************************************"

	rm -Rf "$APP_FOLDER"
	mkdir $BUILD_FOLDER
	cp -R om "$APP_FOLDER"
	rm -R "$APP_FOLDER"/build/
	rm -R "$APP_FOLDER"/resources
echo "=> PACKED IN BUILD FOLDER!"
}

# pack_app MUST have been called before..
set_fonts()
{   
   cp "$APP_FOLDER"/"$APP_NAME".app/Contents/Resources/fonts/mac/* "$APP_FOLDER"/"$APP_NAME".app/Contents/Resources/fonts/
   rm -rf "$APP_FOLDER"/"$APP_NAME".app/Contents/Resources/fonts/mac/
   rm -rf "$APP_FOLDER"/"$APP_NAME".app/Contents/Resources/fonts/win/
   rm -rf "$APP_FOLDER"/"$APP_NAME".app/Contents/Resources/fonts/linux/
	 	   
   cp "$APP_FOLDER"/"$APP_NAME".app/Contents/Info.plist .	   
   defaults write $(pwd)/Info.plist ATSApplicationFontsPath -string "fonts/"
   mv ./Info.plist "$APP_FOLDER"/"$APP_NAME".app/Contents/Info.plist
}

# pack_app MUST have been called before..
create_simple_dmg()
{
echo "***************************************************"
echo "Preparing DMG distribution for $APP_FOLDER"
echo "***************************************************"

	rm -f  "$BUILD_FOLDER"/"$DMG_NAME".dmg	
	rm -rf "$BUILD_FOLDER"/_DMG
	mkdir "$BUILD_FOLDER"/_DMG
	cp -R "$APP_FOLDER" "$BUILD_FOLDER"/_DMG
	#ln -s /Applications/ _DMG/Applications
	
	hdiutil create -fs HFS+ -volname $DMG_NAME -srcfolder "$BUILD_FOLDER"/_DMG "$BUILD_FOLDER"/"$DMG_NAME".dmg
	rm -rf "$BUILD_FOLDER"/_DMG	
}

zip_release()
{
	cd $BUILD_FOLDER
	rm "$APP_NAME".zip
	zip -r "$APP_NAME".zip "$APP_NAME"/  
}

sign_release()
{
	cd .. 
	./codesign-om7
	cd o7  
}

change_permission()
{
    # this function change the permission for a given folder
    # $1 : the folder
    echo "Setting permissions for $1"
    sudo chown -R root "$1"
    sudo chgrp -R admin "$1"
    sudo chmod -R o+rx "$1"
    sudo chmod -R ug+rwx "$1"
}

#=============================
# MAIN SCRIPT
#=============================

if 	[ "$1" = "-d" ]; 	then 	deliver_app
elif	[ "$1" = "-p" ];	then	pack_app; set_fonts
elif	[ "$1" = "-dp" ];	then	deliver_app; pack_app; set_fonts
elif	[ "$1" = "-dmg" ];	then	create_simple_dmg
elif	[ "$1" = "-zip" ];	then	zip_release
elif	[ "$1" = "-sign" ];	then	codesign_release	
elif	[ "$1" = "-dpd" ];	then	deliver_app; pack_app; set_fonts; create_simple_dmg
elif	[ "$1" = "-dpz" ];	then	deliver_app; pack_app; set_fonts; zip_release
elif	[ "$1" = "-all" ];	then	deliver_app; pack_app; set_fonts; sign_release; zip_release
else 	
	echo "Dont'know what to do! :("	
	echo "Options:"
	echo "-d = deliver app"
	echo "-p = pack delivered app as a separate folder (including fonts) "
	echo "-dp = deliver and pack"
	echo "-zip = create ZIP from previously packed app"
	echo "-dmg = create DMG from previously packed app"
	echo "-dpd = deliver, pack and create DMG"
	echo "-dpz = deliver, pack and zip"
	echo "-all = deliver, pack, SIGN and zip"
fi

exit 0







