{include resources/header.md}
{set-property title "metabang-bind - Sticking it the to metal..."}

<div class="contents">
<div class="system-links">

  * [User's guide](user-guide.html)
  * [Issue tracker](https://github.com/gwkkwg/metabang-bind/issues)
  * [Mailing Lists][3]
  * [Getting it][4]
  * [News][6]
  * [Changelog][7]

   [3]: #mailing-lists
   [4]: #downloads
   [5]: documentation/ (documentation link)
   [6]: #news
   [7]: changelog.html


</div>
<div class="system-description">

### What it is

Bind extends the idea of of `let` and destructing to provide
a uniform syntax for all your accessor needs. It combines
_let_, _destructuring-bind_, `with-slots`, `with-accessors`,
structure editing, property or association-lists, and
_multiple-value-bind_ and a whole lot more into a single
form. The [user guide][user-guide] has all the details but
here is example to whet your appetite:

    (bind ((a 2)
           ((b &rest args &key (c 2) &allow-other-keys) '(:a :c 5 :d 10 :e 54))
           ((:values d e) (truncate 4.5)))
      (list a b c d e args))
    ==> (2 :A 5 4 0.5 (:C 5 :D 10 :E 54))

Bind is especially handy when you have more than one layer of
`multiple-value-bind` or `destructuring-bind`. Since `bind` is a
single form, you don't end up too far off to the right in
editor land.

Bind is released under the [MIT license][mit-license].

{anchor mailing-lists}

### Mailing Lists

Use the developer [mailing list][metabang-bind-devel] for any questions or comments regarding bind.

{anchor downloads}

### Where is it

metabang.com is switching from [darcs][] to [git][] for source control; the current metabang-bind repository is on [github][github-metabang-bind] and you can clone it using:

    git clone git://github.com/gwkkwg/metabang-bind

metabang-bind is also [ASDF installable][asdf-install]. Its
CLiki home is right [where][cliki-home] you'd expect.

There's also a handy [gzipped tar file][tarball].

{anchor news}

### What is happening

10 April 2010 - moved to github; added flet support

28 May 2009 - added `:structure/rw` binding form; updated
webpage to link to the user's guide

1 Dec 2007 - Added support for [array
destructuring][array-bindings] (Thanks to Tamas Papp for the
idea)

15 Nov 2007 - New user guide; bind handles structures and
property lists and is now extensible!

13 Nov 2005 - Initial webpage n' stuff.

</div>
</div>

{include resources/footer.md}


